// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Entidade.Models;

public partial class Materium
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public virtual ICollection<Questao> Questaos { get; set; } = new List<Questao>();
}