// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Entidade.Models;

public partial class Questao
{
    public long Id { get; set; }

    public string Nome { get; set; }

    public string Enunciado { get; set; }

    public string Imagem { get; set; }

    public int? Dificuladade { get; set; }

    public bool? QuestaoAtiva { get; set; }

    public int IdMateria { get; set; }

    public virtual Materium IdMateriaNavigation { get; set; }
}